plugins {
	id "com.hypherionmc.modutils.modpublisher" version "${modpublisher_version}"
	id "net.fabricmc.fabric-loom" version "${loom_version}"
	id "maven-publish"
}

version = "mc${project.minecraft_version}-v${project.mod_version}"
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven { url "https://maven.shedaniel.me/" }
	maven { url "https://maven.terraformersmc.com/" }
}

dependencies {
	// Minecraft & Fabric Loader
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	// Mod Menu
	implementation("com.terraformersmc:modmenu:${project.modmenu_version}") {
		exclude(group: "net.fabricmc.fabric-api")
	}

	// Cloth Config
	api("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_version}") {
		exclude(group: "net.fabricmc.fabric-api")
	}
}

processResources {
	inputs.property "mod_version", project.mod_version

	filesMatching("fabric.mod.json") {
		expand "mod_version": project.mod_version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.archives_base_name}"}
	}
}

publisher {
	apiKeys {
		modrinth System.getenv("MODRINTH_TOKEN")
		curseforge System.getenv("CURSE_TOKEN")
		github System.getenv("GITHUB_TOKEN")
	}

	setCurseID("279429")
	setModrinthID("2i7tg1Wv")
	setVersionType("release")
	setVersion("mc${project.minecraft_version}-v${project.mod_version}")
	setDisplayName("v${project.mod_version} (Minecraft ${project.minecraft_version})")
	setChangelog(file("CHANGELOG.md"))
	setGameVersions("26.2")
	setLoaders("fabric")
	setCurseEnvironment("client")
	setArtifact(jar)
	setDisableMalwareScanner(true) // Disable the built in Fractureizer scanner
	setJavaVersions([JavaVersion.VERSION_25]) // Currently only used by CurseForge
	github {
		repo("emonadeo/autorun")
		displayName("v${project.mod_version} (Minecraft ${project.minecraft_version})")
		tag("mc${project.minecraft_version}-v${project.mod_version}")
		createTag(true)
		createRelease(true)
	}
	curseDepends {
		required("fabric-api")
		optional("modmenu")
		optional("cloth-config")
	}
	modrinthDepends {
		required("fabric-api")
		optional("modmenu")
		optional("cloth-config")
	}
}
