name: publish

on:
    push:
        tags:
            - '*'

jobs:
    publish:
        runs-on: ubuntu-22.04
        permissions:
            # needed to create new releases
            contents: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Validate Gradle Wrapper
              uses: gradle/wrapper-validation-action@v1

            - name: Setup Java 21
              uses: actions/setup-java@v4
              with:
                  java-version: 21
                  distribution: 'microsoft'

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4
              with:
                  cache-read-only: false

            - name: Execute Gradle Build
              run: ./gradlew build

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: Artifacts
                  path: build/libs/

            - name: Publish
              uses: Kir-Antipov/mc-publish@v3.3
              with:
                  modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
                  curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
